import { createServer } from 'node:http'
import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { test, expect, BASE_URL, requireMountedPlugin } from './browser-fixture.ts'
import { dismissOnboarding } from './checkpoints-helpers.ts'

test('decision providers persist separate hosted and custom models and evaluate only on request', async ({ page }, info) => {
  requireMountedPlugin('decisions')
  const calls: Array<{ path: string; body: Record<string, unknown> }> = []
  const hostedRequests: string[] = []
  page.on('request', request => { if (request.url().startsWith('https://api.typesafe.ai/')) hostedRequests.push(request.url()) })
  const server = createServer((req, res) => {
    const chunks: Buffer[] = []
    req.on('data', chunk => chunks.push(Buffer.from(chunk)))
    req.on('end', () => {
      const body = JSON.parse(Buffer.concat(chunks).toString('utf8') || '{}') as Record<string, unknown>
      calls.push({ path: req.url ?? '', body })
      if (req.method !== 'POST' || req.url !== '/v1/systemone') { res.writeHead(404); res.end(); return }
      res.writeHead(200, { 'content-type': 'application/json' })
      res.end(JSON.stringify({ model: body.model, answers: { color: { type: 'choice', choice: 'blue', probabilities: { blue: 0.95, green: 0.05 }, confidence: 0.9 } }, usage: { input_tokens: 12, output_tokens: 0 } }))
    })
  })
  await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve))
  const address = server.address()
  if (!address || typeof address === 'string') throw new Error('Local decision fixture did not bind')
  try {
    await page.setViewportSize({ width: 1280, height: 1440 })
    await page.emulateMedia({ colorScheme: 'dark' })
    await page.goto(BASE_URL, { waitUntil: 'domcontentloaded' })
    await dismissOnboarding(page)
    const openModels = async () => {
      const modelsNav = page.getByRole('button', { name: 'Models', exact: true }).first()
      if (!(await modelsNav.isVisible().catch(() => false))) {
        let opened = false
        for (let attempt = 0; attempt < 3; attempt++) {
          await dismissOnboarding(page)
          try {
            await page.getByRole('button', { name: 'Settings', exact: true }).first().click({ timeout: 5000 })
            opened = true
            break
          } catch (error) {
            if (!(await page.getByRole('dialog', { name: 'Internal Testing Notice' }).isVisible().catch(() => false))) throw error
          }
        }
        if (!opened) throw new Error('The Harness onboarding notice blocked Models settings')
      }
      await modelsNav.click()
    }
    await openModels()
    const section = page.getByTestId('dsh-next-decisions')
    const add = section.getByRole('button', { name: 'Add decision model provider', exact: true })
    const addCard = section.getByTestId('decision-add-card')
    const editor = addCard.getByRole('tabpanel').getByTestId('decision-provider-editor')
    const known = addCard.getByRole('tab', { name: 'TypeSafe', exact: true })
    const custom = addCard.getByRole('tab', { name: 'Custom decision API', exact: true })
    await expect(add).toBeEnabled()
    await add.click()
    await expect(addCard.getByRole('tab')).toHaveCount(2)
    await expect(known).toHaveAttribute('aria-selected', 'true')
    await expect(editor.getByLabel('Provider ID', { exact: true })).toHaveValue('typesafe')
    await expect(editor.getByLabel('Provider ID', { exact: true })).toBeDisabled()
    await expect(editor.getByLabel('Base URL', { exact: true })).toHaveValue('https://api.typesafe.ai/v1')
    await expect(editor.getByLabel('Base URL', { exact: true })).toBeDisabled()
    await expect(editor.getByLabel('API key', { exact: true })).toHaveAttribute('required', '')
    await custom.click()
    await expect(custom).toHaveAttribute('aria-selected', 'true')
    await expect(editor.getByLabel('Provider ID', { exact: true })).toHaveValue('')
    await expect(editor.getByLabel('Base URL', { exact: true })).toHaveValue('')
    await editor.getByLabel('Provider ID', { exact: true }).fill('local-decisions')
    await editor.getByLabel('Display name', { exact: true }).fill('Local decision server')
    await editor.getByLabel('Base URL', { exact: true }).fill(`http://127.0.0.1:${address.port}/v1`)
    await editor.getByRole('textbox', { name: 'Model ID 1', exact: true }).fill('kev-4b')
    await editor.getByRole('textbox', { name: 'Display name 1', exact: true }).fill('KEV Compact')
    const firstDetails = editor.getByRole('button', { name: 'Model details 1', exact: true })
    await expect(firstDetails).toHaveAttribute('aria-expanded', 'true')
    await editor.getByRole('textbox', { name: 'Advertised input context for model 1', exact: true }).fill('64K')
    await firstDetails.focus()
    await firstDetails.press('Enter')
    await expect(firstDetails).toHaveAttribute('aria-expanded', 'false')
    await expect(editor.getByRole('textbox', { name: 'Advertised input context for model 1', exact: true })).toHaveCount(0)
    await firstDetails.press('Enter')
    await expect(firstDetails).toBeFocused()
    await expect(firstDetails).toHaveAttribute('aria-expanded', 'true')
    await expect(editor.getByRole('textbox', { name: 'Advertised input context for model 1', exact: true })).toHaveValue('64K')
    await editor.getByRole('button', { name: 'Add model', exact: true }).click()
    await expect(editor.getByRole('textbox', { name: 'Model ID 2', exact: true })).toBeFocused()
    await editor.getByRole('textbox', { name: 'Model ID 2', exact: true }).fill('kev-4b')
    await editor.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(editor.getByRole('alert')).toContainText('unique, non-empty model IDs')
    await editor.getByRole('button', { name: 'Add model', exact: true }).click()
    await editor.getByRole('textbox', { name: 'Model ID 3', exact: true }).fill('kev-9b')
    await editor.getByRole('textbox', { name: 'Display name 3', exact: true }).fill('KEV Extended')
    await editor.getByRole('textbox', { name: 'Advertised input context for model 3', exact: true }).fill('2M')
    await editor.getByRole('button', { name: 'Remove model 2', exact: true }).click()
    await expect(editor.getByRole('textbox', { name: 'Model ID 2', exact: true })).toHaveValue('kev-9b')
    await expect(editor.getByRole('textbox', { name: 'Display name 2', exact: true })).toHaveValue('KEV Extended')
    await expect(editor.getByRole('textbox', { name: 'Advertised input context for model 2', exact: true })).toHaveValue('2M')
    await editor.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(editor.getByRole('alert')).toContainText('positive whole token count up to 1M')
    await editor.getByRole('textbox', { name: 'Advertised input context for model 2', exact: true }).fill('1M')
    await expect(editor.getByRole('alert')).toHaveCount(0)
    await expect(editor.getByLabel('API key', { exact: true })).toHaveValue('')
    await editor.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(addCard).toHaveCount(0)
    await expect(section.getByRole('status')).toContainText('Decision provider saved.')
    expect(calls).toEqual([])
    const home = process.env.DSH_HOME
    if (!home) throw new Error('DSH_HOME is required')
    const profile = readdirSync(join(home, 'profiles'))[0]
    const patch = () => readFileSync(join(home, 'profiles', profile, 'cordis.patch.yml'), 'utf8')
    await expect.poll(patch).toContain('kev-9b')
    await expect.poll(patch).toContain('KEV Compact')
    await expect.poll(patch).toContain('contextWindow: 64000')
    await expect.poll(patch).toContain('KEV Extended')
    await expect.poll(patch).toContain('contextWindow: 1000000')
    expect(patch()).not.toContain('modelIds:')

    await add.click()
    await expect(known).toHaveAttribute('aria-selected', 'true')
    await expect(custom).toHaveAttribute('aria-selected', 'false')
    await editor.getByLabel('API key', { exact: true }).fill('offline-test-only-key')
    await editor.getByRole('textbox', { name: 'Model ID 1', exact: true }).fill('jev-1.13.0')
    await editor.getByRole('textbox', { name: 'Display name 1', exact: true }).fill('JEV 1.13')
    await editor.getByRole('textbox', { name: 'Advertised input context for model 1', exact: true }).fill('64K')
    await editor.getByRole('button', { name: 'Add model', exact: true }).click()
    await editor.getByRole('textbox', { name: 'Model ID 2', exact: true }).fill('jev-preview')
    await editor.getByRole('textbox', { name: 'Display name 2', exact: true }).fill('JEV Preview')
    await editor.getByRole('textbox', { name: 'Advertised input context for model 2', exact: true }).fill('64K')
    const firstModel = editor.locator('li').first()
    await expect(firstModel.getByLabel('Decision output', { exact: true })).toHaveValue('Choice')
    await expect(firstModel.getByLabel('Decision output', { exact: true })).toBeDisabled()
    await expect(firstModel.getByRole('checkbox', { name: 'Text', exact: true })).toBeChecked()
    await expect(firstModel.getByRole('checkbox', { name: 'Text', exact: true })).toBeDisabled()
    await expect(firstModel.getByRole('checkbox', { name: 'Image', exact: true })).not.toBeChecked()
    await expect(firstModel.getByRole('checkbox', { name: 'Image', exact: true })).toBeDisabled()
    for (const theme of ['dark', 'light'] as const) {
      await page.emulateMedia({ colorScheme: theme })
      const image = info.outputPath(`decision-typesafe-preset-${theme}.png`)
      await addCard.screenshot({ path: image, scale: 'css' })
      await info.attach(`decision-typesafe-preset-${theme}`, { path: image, contentType: 'image/png' })
    }
    await page.emulateMedia({ colorScheme: 'dark' })
    await editor.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(section.getByTestId('decision-provider-card')).toHaveCount(2)
    await expect(section.getByRole('status')).toContainText('Decision provider saved.')
    await expect.poll(patch).toContain('jev-preview')
    await expect.poll(patch).toContain('JEV 1.13')
    await expect.poll(patch).toContain('contextWindow: 64000')
    expect(patch()).not.toContain('modelIds:')
    expect(patch()).not.toContain('offline-test-only-key')
    expect(calls).toEqual([])
    await add.click()
    await expect(known).toBeDisabled()
    await expect(custom).toHaveAttribute('aria-selected', 'true')
    await editor.getByRole('button', { name: 'Cancel', exact: true }).click()

    await page.reload({ waitUntil: 'domcontentloaded' })
    await dismissOnboarding(page)
    await openModels()
    const localCard = section.getByTestId('decision-provider-card').filter({ hasText: 'Local decision server' })
    const hostedCard = section.getByTestId('decision-provider-card').filter({ has: page.locator('strong').getByText('TypeSafe', { exact: true }) })
    await expect(section.getByTestId('decision-provider-card')).toHaveCount(2)
    await expect(localCard.getByRole('button', { name: 'Models and test (2)', exact: true })).toHaveAttribute('aria-expanded', 'false')
    await expect(hostedCard.getByRole('button', { name: 'Models and test (2)', exact: true })).toHaveAttribute('aria-expanded', 'false')
    await expect(localCard.locator('code')).toHaveCount(0)
    await expect(hostedCard.getByRole('img', { name: 'API key saved' })).toBeVisible()
    for (const theme of ['dark', 'light'] as const) {
      await page.emulateMedia({ colorScheme: theme })
      const image = info.outputPath(`decision-provider-rows-${theme}.png`)
      await section.screenshot({ path: image, scale: 'css' })
      await info.attach(`decision-provider-rows-${theme}`, { path: image, contentType: 'image/png' })
    }
    await page.emulateMedia({ colorScheme: 'dark' })
    await localCard.getByRole('button', { name: 'Models and test (2)', exact: true }).click()
    await expect(localCard.locator('code').filter({ hasText: 'kev-4b' })).toBeVisible()
    await expect(localCard.getByText('KEV Compact', { exact: true })).toBeVisible()
    await expect(localCard.getByText('64K advertised', { exact: true })).toBeVisible()
    await expect(localCard.getByText('KEV Extended', { exact: true })).toBeVisible()
    await expect(localCard.getByText('1M advertised', { exact: true })).toBeVisible()
    await expect(localCard.getByText(`http://127.0.0.1:${address.port}/v1`, { exact: true })).toBeVisible()
    await expect(localCard.getByText('No API key saved', { exact: true })).toBeVisible()
    await hostedCard.getByRole('button', { name: 'Models and test (2)', exact: true }).click()
    await expect(hostedCard.locator('code').filter({ hasText: 'jev-preview' })).toBeVisible()
    await expect(hostedCard.getByText('JEV Preview', { exact: true })).toBeVisible()
    await expect(hostedCard.getByText('64K advertised', { exact: true })).toHaveCount(2)
    await expect(hostedCard.getByText('API key saved', { exact: true })).toBeVisible()
    for (const theme of ['dark', 'light'] as const) {
      await page.emulateMedia({ colorScheme: theme })
      const image = info.outputPath(`decision-provider-model-details-${theme}.png`)
      await section.screenshot({ path: image, scale: 'css' })
      await info.attach(`decision-provider-model-details-${theme}`, { path: image, contentType: 'image/png' })
    }
    await page.emulateMedia({ colorScheme: 'dark' })
    expect(calls).toEqual([])
    await expect(localCard.getByLabel('Model to test', { exact: true }).locator('option[value="kev-9b"]')).toHaveText('KEV Extended (kev-9b)')
    await localCard.getByLabel('Model to test', { exact: true }).selectOption('kev-9b')
    await localCard.getByRole('button', { name: 'Test decision', exact: true }).click()
    await expect(section.getByRole('status')).toContainText('Valid decision response from kev-9b')
    expect(calls).toHaveLength(1)
    expect(calls[0]).toMatchObject({ path: '/v1/systemone', body: { model: 'kev-9b', state: 'The sky is blue.' } })
    expect(hostedRequests).toEqual([])

    await localCard.getByRole('button', { name: 'Edit Local decision server (local-decisions)', exact: true }).click()
    const inlineEditor = localCard.getByTestId('decision-provider-editor')
    await expect(section.getByTestId('decision-provider-editor')).toHaveCount(1)
    await expect(hostedCard.getByTestId('decision-provider-editor')).toHaveCount(0)
    await expect(inlineEditor.getByLabel('Provider ID', { exact: true })).toHaveValue('local-decisions')
    await expect(inlineEditor.getByLabel('Provider ID', { exact: true })).toBeDisabled()
    await expect(inlineEditor.getByRole('textbox', { name: 'Display name 1', exact: true })).toHaveValue('KEV Compact')
    await inlineEditor.getByRole('textbox', { name: 'Display name 1', exact: true }).fill('KEV Compact edited')
    const editedDetails = inlineEditor.getByRole('button', { name: 'Model details 1', exact: true })
    await expect(editedDetails).toHaveAttribute('aria-expanded', 'false')
    await editedDetails.click()
    await expect(inlineEditor.getByRole('textbox', { name: 'Advertised input context for model 1', exact: true })).toHaveValue('64K')
    await inlineEditor.getByRole('textbox', { name: 'Advertised input context for model 1', exact: true }).fill('96K')
    await inlineEditor.getByRole('button', { name: 'Remove model 2', exact: true }).click()
    await expect(inlineEditor.getByRole('textbox', { name: 'Model ID 1', exact: true })).toHaveValue('kev-4b')
    await inlineEditor.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(inlineEditor).toHaveCount(0)
    await expect.poll(patch).not.toContain('kev-9b')
    await expect.poll(patch).toContain('KEV Compact edited')
    await expect.poll(patch).toContain('contextWindow: 96000')
    expect(patch()).not.toContain('KEV Extended')
    expect(patch()).not.toContain('contextWindow: 1000000')
    const state = await page.request.post(new URL('/dsh-next-decisions/rpc', page.url()).href, { data: { method: 'state' } })
    const result = await state.json()
    expect(result).toMatchObject({ ok: true, value: { writable: true, providers: [
      { id: 'local-decisions', models: [{ id: 'kev-4b', name: 'KEV Compact edited', contextWindow: 96_000 }], keyConfigured: false },
      { id: 'typesafe', models: [
        { id: 'jev-1.13.0', name: 'JEV 1.13', contextWindow: 64_000 },
        { id: 'jev-preview', name: 'JEV Preview', contextWindow: 64_000 },
      ], keyConfigured: true },
    ] } })
    expect(Object.keys(result)).toEqual(['ok', 'value'])
    expect(JSON.stringify(result)).not.toContain('modelIds')
    expect(JSON.stringify(result)).not.toContain('offline-test-only-key')
    expect(JSON.stringify(result)).not.toContain('apiKey')
    await localCard.getByRole('button', { name: 'Remove Local decision server (local-decisions)', exact: true }).click()
    await expect(localCard.getByRole('button', { name: 'Remove provider', exact: true })).toBeVisible()
    await localCard.getByRole('button', { name: 'Cancel', exact: true }).click()
    await expect(section.getByTestId('decision-provider-card')).toHaveCount(2)
    await localCard.getByRole('button', { name: 'Remove Local decision server (local-decisions)', exact: true }).click()
    await localCard.getByRole('button', { name: 'Remove provider', exact: true }).click()
    await expect(section.getByTestId('decision-provider-card')).toHaveCount(1)
    await expect.poll(patch).not.toContain('local-decisions')
    expect(patch()).toContain('jev-preview')
    await section.getByRole('button', { name: 'Refresh', exact: true }).click()
    await expect(section.getByRole('status')).toHaveCount(0)
    const hostedShot = info.outputPath('decision-hosted-card-dark.png')
    await section.screenshot({ path: hostedShot, scale: 'css' })
    await info.attach('decision-hosted-card-dark', { path: hostedShot, contentType: 'image/png' })
    await hostedCard.getByRole('button', { name: 'Remove TypeSafe (typesafe)', exact: true }).click()
    await hostedCard.getByRole('button', { name: 'Remove provider', exact: true }).click()
    await expect(section.getByTestId('decision-provider-card')).toHaveCount(0)
    await expect.poll(patch).not.toContain('typesafe')
    expect(calls).toHaveLength(1)
    expect(hostedRequests).toEqual([])
  } finally {
    server.closeAllConnections()
    await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve()))
  }
})
