import * as React from 'react'
import { act } from 'react'
import { createRoot, type Root } from 'react-dom/client'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { ProvidersSection } from '../src/client/providers/ProvidersSection.tsx'
import { ProviderEditor } from '../src/client/providers/ProviderEditor.tsx'
import { englishTranslate as t, interpolate, en, zh } from '../src/client/dictionaries.ts'
import { DEFAULT_BASE_URL, DecisionError, type ProvidersState, type ProviderChange } from '../src/core/types.ts'
import type { DecisionApi } from '../src/client/api.ts'
import { apply, inject } from '../src/client/index.ts'
import type { Context } from '@deepseek-ai/cordis'

vi.mock('@deepseek-ai/dsh-client-ui-primitives', async importOriginal => ({ ...await importOriginal<typeof import('@deepseek-ai/dsh-client-ui-primitives')>(), IconPlusOutlineRegular: () => <svg aria-hidden="true" />, IconTrashOutlineRegular: () => <svg aria-hidden="true" /> }))
const provider = { id: 'typesafe', name: 'TypeSafe', baseUrl: DEFAULT_BASE_URL, models: [{ id: 'jev-1.13.0', name: 'JEV 1.13', contextWindow: 64_000 }, { id: 'jev-preview', name: 'JEV Preview', contextWindow: 128_000 }], keyConfigured: true }
const local = { id: 'local-decisions', name: 'Local decision server', baseUrl: 'http://127.0.0.1:8009/v1', models: [{ id: 'kev-4b', name: 'KEV Compact', contextWindow: 1_000_000 }, { id: 'kev-9b' }], keyConfigured: false }
const empty: ProvidersState = { providers: [], writable: true, revision: 'r1' }
const saved: ProvidersState = { providers: [provider], writable: true, revision: 'r2' }
let container: HTMLDivElement
let root: Root
beforeEach(() => { vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT', true); container = document.createElement('div'); document.body.append(container); root = createRoot(container) })
afterEach(async () => { await act(async () => root.unmount()); container.remove(); vi.restoreAllMocks() })
const render = async (node: React.ReactNode) => { await act(async () => root.render(node)) }
const card = (id: string) => [...container.querySelectorAll<HTMLElement>('[data-testid="decision-provider-card"]')].find(item => item.textContent?.includes(id))!
const activeEditor = () => container.querySelector<HTMLFormElement>('[role="tabpanel"]:not([hidden]) form') ?? container.querySelector<HTMLFormElement>('form')!
const button = (name: string, scope: ParentNode = container) => [...scope.querySelectorAll<HTMLButtonElement>('button')].find(item => item.textContent?.trim() === name)!
const click = async (name: string, scope: ParentNode = container) => { const target = button(name, scope); expect(target, `${name} button exists`).toBeDefined(); await act(async () => target.click()) }
const tab = (name: string) => [...container.querySelectorAll<HTMLButtonElement>('[role="tab"]')].find(item => item.textContent?.trim() === name)!
const choose = async (name: string) => { const target = tab(name); expect(target).toBeDefined(); await act(async () => target.click()) }
const editorInput = (label: string) => [...activeEditor().querySelectorAll('label')].find(item => item.querySelector('span')?.textContent === label)!.querySelector('input') as HTMLInputElement
async function input(label: string, value: string, form: ParentNode = activeEditor()) {
  const element = [...form.querySelectorAll('label')].find(item => item.querySelector('span')?.textContent === label)!.querySelector('input, textarea')! as HTMLInputElement | HTMLTextAreaElement
  await act(async () => {
    const prototype = element instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype
    Object.getOwnPropertyDescriptor(prototype, 'value')!.set!.call(element, value)
    element.dispatchEvent(new Event('input', { bubbles: true }))
    element.dispatchEvent(new Event('change', { bubbles: true }))
  })
}
async function modelField(key: 'modelId' | 'modelName' | 'modelContext', index: number, value: string, form: ParentNode = activeEditor()) {
  const element = form.querySelector(`input[aria-label="${t(key, { index })}"]`) as HTMLInputElement
  expect(element, `${key} row ${index} exists`).not.toBeNull()
  await act(async () => {
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')!.set!.call(element, value)
    element.dispatchEvent(new Event('input', { bubbles: true }))
    element.dispatchEvent(new Event('change', { bubbles: true }))
  })
}
const modelInput = (index: number, value: string, form?: ParentNode) => modelField('modelId', index, value, form)
const modelNameInput = (index: number, value: string, form?: ParentNode) => modelField('modelName', index, value, form)
const modelContextInput = (index: number, value: string, form?: ParentNode) => modelField('modelContext', index, value, form)
const rowDetails = (index: number, form: ParentNode = activeEditor()) => form.querySelector<HTMLButtonElement>(`button[aria-label="${t('modelDetails', { index })}"]`)!
async function submit(form: HTMLFormElement = activeEditor()) { await act(async () => { form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true })) }) }
function apiFixture(initial: ProvidersState = empty) {
  return { state: vi.fn().mockResolvedValue(initial), save: vi.fn().mockResolvedValue(saved), remove: vi.fn().mockResolvedValue({ ...empty, revision: 'r3' }), test: vi.fn().mockResolvedValue({ model: 'jev-1.13.0', elapsedMs: 42 }) } as unknown as DecisionApi & { [K in keyof DecisionApi]: ReturnType<typeof vi.fn> }
}

describe('provider configuration UI', () => {
  it('defaults to the fixed hosted TypeSafe preset, requires a key, and saves explicit IDs without discovery', async () => {
    const api = apiFixture()
    await render(<ProvidersSection api={api} t={t} />)
    expect(container.textContent).toContain(t('intro'))
    expect(container.textContent).not.toContain('Fetch available models')
    await click(t('add'))
    expect(container.querySelectorAll('[role="tab"]')).toHaveLength(2)
    expect(tab(t('knownMode')).getAttribute('aria-selected')).toBe('true')
    expect(tab(t('customMode')).getAttribute('aria-selected')).toBe('false')
    expect(activeEditor().querySelector<HTMLInputElement>(`input[aria-label="${t('id')}"]`)).toMatchObject({ value: 'typesafe', disabled: true })
    expect(activeEditor().querySelector<HTMLInputElement>(`input[aria-label="${t('baseUrl')}"]`)).toMatchObject({ value: DEFAULT_BASE_URL, disabled: true })
    expect(activeEditor().querySelector<HTMLInputElement>(`input[aria-label="${t('apiKey')}"]`)?.required).toBe(true)
    await modelInput(1, 'jev-1.13.0')
    await modelNameInput(1, 'JEV 1.13')
    expect(rowDetails(1).getAttribute('aria-expanded')).toBe('true')
    await modelContextInput(1, '64K')
    await submit()
    expect(activeEditor().textContent).toContain(t('error.keyRequired'))
    expect(api.save).not.toHaveBeenCalled()
    await click(t('addModel'), activeEditor()); await modelInput(2, 'jev-preview'); await input(t('apiKey'), 'secret-key')
    await submit()
    expect(api.save).toHaveBeenCalledWith({ mode: 'create', revision: 'r1', apiKey: 'secret-key', provider: { id: 'typesafe', name: 'TypeSafe', baseUrl: DEFAULT_BASE_URL, models: [{ id: 'jev-1.13.0', name: 'JEV 1.13', contextWindow: 64_000 }, { id: 'jev-preview' }] } }, expect.any(AbortSignal))
    expect(api.save.mock.calls[0][0].provider).not.toHaveProperty('modelIds')
    expect(container.textContent).not.toContain('secret-key')
    expect(container.querySelector('form')).toBeNull()
    expect(card('TypeSafe').textContent).toContain(t('modelsAndTest', { count: 2 }))
    expect(card('TypeSafe').textContent).not.toContain('jev-1.13.0')
    expect(api.test).not.toHaveBeenCalled()
    expect(api.state).toHaveBeenCalledTimes(1)
  })
  it('uses the native segmented control keyboard and panel semantics', async () => {
    await render(<ProvidersSection api={apiFixture()} t={t} />)
    await click(t('add'))
    const known = tab(t('knownMode'))
    const custom = tab(t('customMode'))
    expect(known.tabIndex).toBe(0)
    expect(custom.tabIndex).toBe(-1)
    expect(document.getElementById(known.getAttribute('aria-controls')!)?.getAttribute('aria-labelledby')).toBe(known.id)
    expect(document.getElementById(custom.getAttribute('aria-controls')!)?.getAttribute('aria-labelledby')).toBe(custom.id)
    await act(async () => { known.focus(); known.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true })) })
    expect(custom.getAttribute('aria-selected')).toBe('true')
    expect(document.activeElement).toBe(custom)
    expect(document.getElementById(known.getAttribute('aria-controls')!)?.hidden).toBe(true)
    expect(document.getElementById(custom.getAttribute('aria-controls')!)?.hidden).toBe(false)
    await act(async () => { custom.dispatchEvent(new KeyboardEvent('keydown', { key: 'Home', bubbles: true })) })
    expect(known.getAttribute('aria-selected')).toBe('true')
    expect(document.activeElement).toBe(known)
  })
  it('preserves independent hosted and custom drafts when switching, and allows a keyless custom loopback endpoint', async () => {
    const api = apiFixture()
    api.save.mockResolvedValueOnce({ providers: [local], writable: true, revision: 'r2' })
    await render(<ProvidersSection api={api} t={t} />)
    await click(t('add'))
    await input(t('name'), 'My TypeSafe'); await modelInput(1, 'jev-preview'); await modelNameInput(1, 'Preview label'); await modelContextInput(1, '128K'); await input(t('apiKey'), 'draft-key')
    await choose(t('customMode'))
    expect(tab(t('customMode')).getAttribute('aria-selected')).toBe('true')
    expect(activeEditor().querySelector<HTMLInputElement>(`input[aria-label="${t('id')}"]`)).toMatchObject({ value: '', disabled: false })
    expect(activeEditor().querySelector<HTMLInputElement>(`input[aria-label="${t('baseUrl')}"]`)).toMatchObject({ value: '', disabled: false })
    expect(activeEditor().querySelector<HTMLInputElement>(`input[aria-label="${t('apiKey')}"]`)?.required).toBe(false)
    await input(t('id'), 'local-decisions'); await input(t('name'), 'Local decision server'); await input(t('baseUrl'), local.baseUrl); await modelInput(1, 'kev-4b')
    await modelNameInput(1, 'KEV Compact'); await modelContextInput(1, '1M')
    await choose(t('knownMode'))
    expect(editorInput(t('name')).value).toBe('My TypeSafe')
    expect(activeEditor().querySelector<HTMLInputElement>(`input[aria-label="${t('apiKey')}"]`)?.value).toBe('draft-key')
    expect(activeEditor().querySelector<HTMLInputElement>(`input[aria-label="${t('modelId', { index: 1 })}"]`)?.value).toBe('jev-preview')
    expect(activeEditor().querySelector<HTMLInputElement>(`input[aria-label="${t('modelName', { index: 1 })}"]`)?.value).toBe('Preview label')
    expect(activeEditor().querySelector<HTMLInputElement>(`input[aria-label="${t('modelContext', { index: 1 })}"]`)?.value).toBe('128K')
    await choose(t('customMode'))
    expect(activeEditor().querySelector<HTMLInputElement>(`input[aria-label="${t('id')}"]`)?.value).toBe('local-decisions')
    expect(activeEditor().querySelector<HTMLInputElement>(`input[aria-label="${t('baseUrl')}"]`)?.value).toBe(local.baseUrl)
    expect(activeEditor().querySelector<HTMLInputElement>(`input[aria-label="${t('modelId', { index: 1 })}"]`)?.value).toBe('kev-4b')
    expect(activeEditor().querySelector<HTMLInputElement>(`input[aria-label="${t('modelName', { index: 1 })}"]`)?.value).toBe('KEV Compact')
    expect(activeEditor().querySelector<HTMLInputElement>(`input[aria-label="${t('modelContext', { index: 1 })}"]`)?.value).toBe('1M')
    await submit()
    expect(api.save).toHaveBeenCalledWith({ mode: 'create', revision: 'r1', provider: { id: 'local-decisions', name: 'Local decision server', baseUrl: local.baseUrl, models: [{ id: 'kev-4b', name: 'KEV Compact', contextWindow: 1_000_000 }] } }, expect.any(AbortSignal))
    expect(api.save.mock.calls[0][0]).not.toHaveProperty('apiKey')
    expect(container.textContent).not.toContain('draft-key')
  })
  it('starts a subsequent add in custom mode and disables the existing TypeSafe preset', async () => {
    const api = apiFixture(saved)
    await render(<ProvidersSection api={api} t={t} />)
    await click(t('add'))
    expect(tab(t('knownMode')).disabled).toBe(true)
    expect(tab(t('knownMode')).getAttribute('aria-selected')).toBe('false')
    expect(tab(t('customMode')).getAttribute('aria-selected')).toBe('true')
    expect(activeEditor().querySelector<HTMLInputElement>(`input[aria-label="${t('id')}"]`)?.value).toBe('')
    expect(activeEditor().querySelector<HTMLInputElement>(`input[aria-label="${t('baseUrl')}"]`)?.value).toBe('')
    await choose(t('knownMode'))
    expect(tab(t('customMode')).getAttribute('aria-selected')).toBe('true')
    expect(api.save).not.toHaveBeenCalled()
  })
  it.each(['known', 'custom', 'both'] as const)('prompts once when closing an add with %s mode dirty', async mode => {
    const api = apiFixture()
    const confirm = vi.spyOn(window, 'confirm').mockReturnValue(false)
    await render(<ProvidersSection api={api} t={t} />)
    await click(t('add'))
    if (mode !== 'custom') await modelNameInput(1, 'Known model draft')
    await choose(t('customMode'))
    if (mode !== 'known') await modelContextInput(1, '64K')
    if (mode === 'custom') await choose(t('knownMode'))
    await click(t('cancel'), activeEditor())
    expect(confirm).toHaveBeenCalledExactlyOnceWith(t('discard'))
    expect(container.querySelector('[data-testid="decision-add-card"]')).not.toBeNull()
    confirm.mockReturnValue(true)
    await click(t('cancel'), activeEditor())
    expect(confirm).toHaveBeenCalledTimes(2)
    expect(container.querySelector('[data-testid="decision-add-card"]')).toBeNull()
    await click(t('add'))
    expect(tab(t('knownMode')).getAttribute('aria-selected')).toBe('true')
    expect(editorInput(t('name')).value).toBe(t('knownProviderName'))
  })
  it('keeps the captured revision and immutable ID when editing inline; a blank key preserves it', async () => {
    const api = apiFixture({ ...saved, providers: [provider, local] })
    await render(<ProvidersSection api={api} t={t} />)
    const hostedCard = card('TypeSafe')
    const localCard = card('Local decision server')
    await click(t('edit'), hostedCard)
    expect(hostedCard.querySelector('form')).not.toBeNull()
    expect(localCard.querySelector('form')).toBeNull()
    expect(hostedCard.querySelector<HTMLInputElement>(`input[aria-label="${t('id')}"]`)).toMatchObject({ value: 'typesafe', disabled: true })
    expect(hostedCard.querySelector<HTMLInputElement>(`input[aria-label="${t('baseUrl')}"]`)).toMatchObject({ value: DEFAULT_BASE_URL, disabled: true })
    expect(hostedCard.textContent).toContain(t('keyPresetEditHint'))
    await input(t('name'), 'New name', hostedCard); await submit(hostedCard.querySelector('form')!)
    expect(api.save.mock.calls[0][0]).toMatchObject({ mode: 'edit', revision: 'r2', provider: { id: 'typesafe', name: 'New name', models: provider.models } })
    expect(api.save.mock.calls[0][0]).not.toHaveProperty('apiKey')
    expect(api.save.mock.calls[0][0].provider).not.toHaveProperty('modelIds')
  })
  it('cancels only the inline edit after one discard prompt and restores its row', async () => {
    const api = apiFixture({ ...saved, providers: [provider, local] })
    const confirm = vi.spyOn(window, 'confirm').mockReturnValue(false)
    await render(<ProvidersSection api={api} t={t} />)
    const localCard = card('Local decision server')
    await click(t('modelsAndTest', { count: 2 }), localCard)
    await click(t('edit'), localCard)
    await input(t('name'), 'Unsaved local name', localCard)
    await click(t('cancel'), localCard)
    expect(confirm).toHaveBeenCalledExactlyOnceWith(t('discard'))
    expect(localCard.querySelector('form')).not.toBeNull()
    confirm.mockReturnValue(true)
    await click(t('cancel'), localCard)
    expect(localCard.querySelector('form')).toBeNull()
    expect(localCard.textContent).toContain('Local decision server')
    expect(localCard.textContent).toContain('kev-4b')
    expect(localCard.textContent).toContain('KEV Compact')
    expect(localCard.textContent).toContain(t('contextSummary', { capacity: '1M' }))
    expect(card('TypeSafe').querySelector('form')).toBeNull()
    expect(api.save).not.toHaveBeenCalled()
  })
  it('validates duplicate explicit IDs and reports host conflicts without closing the custom editor', async () => {
    const api = apiFixture()
    await render(<ProvidersSection api={api} t={t} />)
    await click(t('add')); await choose(t('customMode'))
    await input(t('id'), 'local'); await input(t('name'), 'Local'); await input(t('baseUrl'), local.baseUrl)
    await modelInput(1, 'kev'); await click(t('addModel'), activeEditor()); await modelInput(2, 'kev'); await submit()
    expect(activeEditor().textContent).toContain(t('error.invalid-models'))
    expect(api.save).not.toHaveBeenCalled()
    await modelInput(2, 'kev-other')
    expect(activeEditor().querySelector('[role="alert"]')).toBeNull()
    api.save.mockRejectedValueOnce(new DecisionError('conflict'))
    await submit()
    expect(container.textContent).toContain(t('error.conflict'))
    expect(activeEditor()).not.toBeNull()
  })
  it.each(['0', '1000001', '1001K', '2M', '1.5K', '-1', '1e3', 'invalid'])('rejects invalid advertised context %s with a localized error without saving', async context => {
    const save = vi.fn()
    await render(<ProviderEditor provider={provider} revision="r2" busy={false} t={t} onSave={save} onCancel={vi.fn()} />)
    expect(rowDetails(1).getAttribute('aria-expanded')).toBe('false')
    await act(async () => rowDetails(1).click())
    await modelContextInput(1, context)
    await submit()
    expect(container.querySelector('[role="alert"]')?.textContent).toBe(t('error.invalid-context'))
    expect(save).not.toHaveBeenCalled()
  })
  it('discloses model details by keyboard focus and shows text-only input with Choice output', async () => {
    await render(<ProviderEditor provider={provider} revision="r2" busy={false} t={t} onSave={vi.fn()} onCancel={vi.fn()} />)
    const details = rowDetails(1)
    expect(details.getAttribute('aria-expanded')).toBe('false')
    expect(details.getAttribute('aria-controls')).toBeNull()
    expect(container.querySelector(`input[aria-label="${t('modelContext', { index: 1 })}"]`)).toBeNull()
    await act(async () => { details.focus(); details.click() })
    expect(document.activeElement).toBe(details)
    expect(details.getAttribute('aria-expanded')).toBe('true')
    expect(document.getElementById(details.getAttribute('aria-controls')!)).not.toBeNull()
    expect(container.querySelector<HTMLInputElement>(`input[aria-label="${t('modelContext', { index: 1 })}"]`)?.value).toBe('64K')
    const row = details.closest('li')!
    const output = [...row.querySelectorAll('label')].find(item => item.querySelector('span')?.textContent === t('outputType'))?.querySelector('input')
    expect(output).toMatchObject({ value: t('outputChoice'), disabled: true, readOnly: true })
    const inputs = [...row.querySelectorAll('fieldset[disabled] label')].filter(label => label.textContent === t('inputText') || label.textContent === t('inputImage'))
    expect(inputs.map(label => ({ type: label.textContent, checked: label.querySelector('input')?.checked, disabled: label.querySelector('input')?.matches(':disabled') }))).toEqual([
      { type: t('inputText'), checked: true, disabled: true }, { type: t('inputImage'), checked: false, disabled: true },
    ])
    expect(row.querySelector('input[type="file"]')).toBeNull()
    expect(row.textContent).toContain(t('inputHint'))
    await act(async () => details.click())
    expect(details.getAttribute('aria-expanded')).toBe('false')
    expect(row.querySelector(`input[aria-label="${t('modelContext', { index: 1 })}"]`)).toBeNull()
  })
  it('adds and removes model rows without losing surviving row values or focus', async () => {
    const save = vi.fn()
    await render(<ProviderEditor provider={provider} revision="r2" busy={false} t={t} onSave={save} onCancel={vi.fn()} />)
    const first = container.querySelector<HTMLInputElement>(`input[aria-label="${t('modelId', { index: 1 })}"]`)
    await click(t('addModel'))
    expect(document.activeElement).toBe(container.querySelector(`input[aria-label="${t('modelId', { index: 3 })}"]`))
    await modelInput(3, 'jev-next')
    await act(async () => rowDetails(1).click())
    const firstContext = container.querySelector<HTMLInputElement>(`input[aria-label="${t('modelContext', { index: 1 })}"]`)!
    const thirdContext = container.querySelector<HTMLInputElement>(`input[aria-label="${t('modelContext', { index: 3 })}"]`)!
    expect(firstContext.getAttribute('aria-describedby')).not.toBe(thirdContext.getAttribute('aria-describedby'))
    expect(document.getElementById(firstContext.getAttribute('aria-describedby')!)?.textContent).toBe(t('contextHint'))
    expect(document.getElementById(thirdContext.getAttribute('aria-describedby')!)?.textContent).toBe(t('contextHint'))
    await modelNameInput(3, 'JEV Next')
    await modelContextInput(3, '999999')
    await act(async () => container.querySelector<HTMLButtonElement>(`button[aria-label="${t('removeModel', { index: 2 })}"]`)!.click())
    expect(container.querySelector<HTMLInputElement>(`input[aria-label="${t('modelId', { index: 1 })}"]`)).toBe(first)
    expect(container.querySelector<HTMLInputElement>(`input[aria-label="${t('modelId', { index: 2 })}"]`)?.value).toBe('jev-next')
    expect(container.querySelector<HTMLInputElement>(`input[aria-label="${t('modelName', { index: 2 })}"]`)?.value).toBe('JEV Next')
    expect(container.querySelector<HTMLInputElement>(`input[aria-label="${t('modelContext', { index: 2 })}"]`)?.value).toBe('999999')
    await submit()
    const change = save.mock.calls[0][0] as ProviderChange
    expect(change.provider.models).toEqual([provider.models[0], { id: 'jev-next', name: 'JEV Next', contextWindow: 999_999 }])
    expect(change.provider).not.toHaveProperty('modelIds')
  })
  it('edits and clears optional model metadata without changing the inference IDs', async () => {
    const save = vi.fn()
    await render(<ProviderEditor provider={provider} revision="r2" busy={false} t={t} onSave={save} onCancel={vi.fn()} />)
    await modelNameInput(1, '')
    await act(async () => rowDetails(1).click())
    await modelContextInput(1, '')
    await modelNameInput(2, 'JEV Preview Plus')
    await act(async () => rowDetails(2).click())
    await modelContextInput(2, '256K')
    await submit()
    expect((save.mock.calls[0][0] as ProviderChange).provider.models).toEqual([
      { id: 'jev-1.13.0' }, { id: 'jev-preview', name: 'JEV Preview Plus', contextWindow: 256_000 },
    ])
  })
  it.each(['name', 'context', 'deletion'])('treats an unsaved model %s as dirty before closing', async edit => {
    const cancel = vi.fn()
    const confirm = vi.spyOn(window, 'confirm').mockReturnValue(false)
    await render(<ProviderEditor provider={provider} revision="r2" busy={false} t={t} onSave={vi.fn()} onCancel={cancel} />)
    if (edit === 'name') await modelNameInput(1, 'Revised model')
    if (edit === 'context') { await act(async () => rowDetails(1).click()); await modelContextInput(1, '96K') }
    if (edit === 'deletion') await act(async () => container.querySelector<HTMLButtonElement>(`button[aria-label="${t('removeModel', { index: 2 })}"]`)!.click())
    const unload = new Event('beforeunload', { cancelable: true }); window.dispatchEvent(unload)
    expect(unload.defaultPrevented).toBe(true)
    await click(t('cancel'))
    expect(confirm).toHaveBeenCalledExactlyOnceWith(t('discard'))
    expect(cancel).not.toHaveBeenCalled()
    confirm.mockReturnValue(true)
    await click(t('cancel'))
    expect(cancel).toHaveBeenCalledOnce()
  })
  it('requires at least one model and caps manual rows at 100', async () => {
    const save = vi.fn()
    await render(<ProviderEditor provider={provider} revision="r2" busy={false} t={t} onSave={save} onCancel={vi.fn()} />)
    await act(async () => container.querySelector<HTMLButtonElement>(`button[aria-label="${t('removeModel', { index: 1 })}"]`)!.click())
    await act(async () => container.querySelector<HTMLButtonElement>(`button[aria-label="${t('removeModel', { index: 1 })}"]`)!.click())
    expect(container.textContent).toContain(t('modelsEmpty'))
    await submit()
    expect(save).not.toHaveBeenCalled()
    expect(container.textContent).toContain(t('error.invalid-models'))
    await click(t('addModel'))
    await modelInput(1, 'jev-recovered')
    await submit()
    expect((save.mock.calls[0][0] as ProviderChange).provider.models).toEqual([{ id: 'jev-recovered' }])
    await render(<ProviderEditor key="many" provider={{ ...provider, models: Array.from({ length: 100 }, (_, index) => ({ id: `jev-${index}` })) }} revision="r2" busy={false} t={t} onSave={save} onCancel={vi.fn()} />)
    expect(button(t('addModel')).disabled).toBe(true)
    expect(container.querySelectorAll('input[aria-label^="Model ID "]')).toHaveLength(100)
  })
  it('renders compact independent provider rows, toggles model details, and edits only the selected card', async () => {
    const api = apiFixture({ ...saved, providers: [provider, local] })
    await render(<ProvidersSection api={api} t={t} />)
    const cards = container.querySelectorAll<HTMLElement>('[data-testid="decision-provider-card"]')
    expect(cards).toHaveLength(2)
    expect(cards[0].textContent).toContain(t('modelsAndTest', { count: 2 }))
    expect(cards[1].textContent).toContain(t('modelsAndTest', { count: 2 }))
    expect(cards[0].textContent).not.toContain('jev-1.13.0')
    expect(cards[1].textContent).not.toContain('kev-4b')
    const disclosure = button(t('modelsAndTest', { count: 2 }), cards[1])
    expect(disclosure.getAttribute('aria-expanded')).toBe('false')
    await click(t('modelsAndTest', { count: 2 }), cards[1])
    expect(disclosure.getAttribute('aria-expanded')).toBe('true')
    expect(cards[1].textContent).toContain('kev-4b')
    expect(cards[1].textContent).toContain('KEV Compact')
    expect(cards[1].textContent).toContain(t('contextSummary', { capacity: '1M' }))
    expect(cards[1].textContent).not.toContain(t('contextSummary', { capacity: '64K' }))
    expect(cards[1].textContent).toContain(local.baseUrl)
    expect(cards[1].textContent).toContain(t('keyMissing'))
    expect(cards[0].textContent).not.toContain('jev-1.13.0')
    await click(t('modelsAndTest', { count: 2 }), cards[1])
    expect(disclosure.getAttribute('aria-expanded')).toBe('false')
    expect(cards[1].textContent).not.toContain('kev-4b')
    await click(t('edit'), cards[1])
    expect(cards[0].querySelector('form')).toBeNull()
    expect(cards[1].querySelector<HTMLInputElement>(`input[aria-label="${t('id')}"]`)?.value).toBe('local-decisions')
    expect(cards[1].querySelector<HTMLInputElement>(`input[aria-label="${t('baseUrl')}"]`)?.disabled).toBe(false)
    await submit(cards[1].querySelector('form')!)
    expect(api.save.mock.calls[0][0]).toMatchObject({ revision: 'r2', mode: 'edit', provider: { id: 'local-decisions', models: local.models } })
  })
  it('names each provider action uniquely and describes credential indicators without claiming connection', async () => {
    const api = apiFixture({ ...saved, providers: [provider, local] })
    await render(<ProvidersSection api={api} t={t} />)
    const hosted = card('TypeSafe')
    const custom = card('Local decision server')
    expect(hosted.querySelector(`button[aria-label="${t('editProvider', { name: provider.name, id: provider.id })}"]`)).not.toBeNull()
    expect(hosted.querySelector(`button[aria-label="${t('removeProvider', { name: provider.name, id: provider.id })}"]`)).not.toBeNull()
    expect(custom.querySelector(`button[aria-label="${t('editProvider', { name: local.name, id: local.id })}"]`)).not.toBeNull()
    expect(custom.querySelector(`button[aria-label="${t('removeProvider', { name: local.name, id: local.id })}"]`)).not.toBeNull()
    expect(hosted.querySelector(`[role="img"][title="${t('keyConfigured')}"]`)).not.toBeNull()
    expect(custom.querySelector('[role="img"]')).toBeNull()
  })
  it('requires confirmation before removing and sends the captured revision', async () => {
    const api = apiFixture(saved)
    await render(<ProvidersSection api={api} t={t} />)
    await click(t('remove'), card('TypeSafe')); expect(api.remove).not.toHaveBeenCalled()
    expect(card('TypeSafe').textContent).toContain(t('removeConfirm', { name: provider.name }))
    await click(t('cancel'), card('TypeSafe')); expect(api.remove).not.toHaveBeenCalled()
    await click(t('remove'), card('TypeSafe')); await click(t('confirmRemove'), card('TypeSafe'))
    expect(api.remove).toHaveBeenCalledWith('typesafe', 'r2', expect.any(AbortSignal))
    expect(container.textContent).toContain(t('removed'))
    expect(container.querySelector('[data-testid="decision-provider-card"]')).toBeNull()
  })
  it('keeps a failed provider removal visible and retryable without claiming success', async () => {
    const api = apiFixture(saved)
    api.remove.mockRejectedValueOnce(new DecisionError('configuration'))
    await render(<ProvidersSection api={api} t={t} />)
    await click(t('remove'), card('TypeSafe'))
    await click(t('confirmRemove'), card('TypeSafe'))
    expect(container.textContent).toContain(t('error.configuration'))
    expect(container.textContent).not.toContain(t('removed'))
    expect(card('TypeSafe').textContent).toContain(t('removeConfirm', { name: provider.name }))
    expect(button(t('confirmRemove'), card('TypeSafe')).disabled).toBe(false)
    await click(t('confirmRemove'), card('TypeSafe'))
    expect(api.remove).toHaveBeenCalledTimes(2)
    expect(container.textContent).toContain(t('removed'))
    expect(container.textContent).not.toContain(t('error.configuration'))
    expect(container.querySelector('[data-testid="decision-provider-card"]')).toBeNull()
  })
  it('tests only the selected saved ID after disclosure and makes no accuracy claim', async () => {
    const api = apiFixture(saved)
    await render(<ProvidersSection api={api} t={t} />)
    expect(card('TypeSafe').querySelector('select')).toBeNull()
    await click(t('modelsAndTest', { count: 2 }), card('TypeSafe'))
    const select = card('TypeSafe').querySelector('select')!
    expect([...select.options].map(option => ({ value: option.value, label: option.textContent }))).toEqual([
      { value: 'jev-1.13.0', label: 'JEV 1.13 (jev-1.13.0)' },
      { value: 'jev-preview', label: 'JEV Preview (jev-preview)' },
    ])
    expect(card('TypeSafe').textContent).toContain(t('contextSummary', { capacity: '64K' }))
    await act(async () => { select.value = 'jev-preview'; select.dispatchEvent(new Event('change', { bubbles: true })) })
    await click(t('test'), card('TypeSafe'))
    expect(api.test).toHaveBeenCalledWith('typesafe', 'jev-preview', expect.any(AbortSignal))
    expect(api.test.mock.calls[0][1]).not.toBe('JEV Preview')
    expect(container.textContent).toContain(t('testResult', { model: 'jev-1.13.0', milliseconds: 42 }))
    expect(card('TypeSafe').textContent).toContain(t('testHint'))
  })
  it('retains the model details after a failed sample and permits retry without false success', async () => {
    const api = apiFixture(saved)
    api.test.mockRejectedValueOnce(new DecisionError('http'))
    await render(<ProvidersSection api={api} t={t} />)
    const hosted = card('TypeSafe')
    await click(t('modelsAndTest', { count: 2 }), hosted)
    const select = hosted.querySelector<HTMLSelectElement>('select')!
    await act(async () => { select.value = 'jev-preview'; select.dispatchEvent(new Event('change', { bubbles: true })) })
    await click(t('test'), hosted)
    expect(container.textContent).toContain(t('error.http'))
    expect(container.textContent).not.toContain('Valid decision response')
    expect(button(t('modelsAndTest', { count: 2 }), hosted).getAttribute('aria-expanded')).toBe('true')
    expect(hosted.querySelector<HTMLSelectElement>('select')?.value).toBe('jev-preview')
    expect(button(t('test'), hosted).disabled).toBe(false)
    await click(t('test'), hosted)
    expect(api.test).toHaveBeenCalledTimes(2)
    expect(container.textContent).toContain(t('testResult', { model: 'jev-1.13.0', milliseconds: 42 }))
    expect(container.textContent).not.toContain(t('error.http'))
  })
  it('locks compact row actions during testing while retaining a working cancel button', async () => {
    const api = apiFixture(saved)
    let finish!: (value: unknown) => void
    api.test.mockImplementation(() => new Promise(resolve => { finish = resolve }))
    await render(<ProvidersSection api={api} t={t} />)
    const hosted = card('TypeSafe')
    await click(t('modelsAndTest', { count: 2 }), hosted)
    await click(t('test'), hosted)
    expect(button(t('refresh')).disabled).toBe(true)
    expect(button(t('add')).disabled).toBe(true)
    expect(button(t('edit'), hosted).disabled).toBe(true)
    expect(button(t('remove'), hosted).disabled).toBe(true)
    expect(button(t('modelsAndTest', { count: 2 }), hosted).disabled).toBe(true)
    expect(button(t('test'), hosted).disabled).toBe(true)
    expect(button(t('cancel'), hosted).disabled).toBe(false)
    await click(t('cancel'), hosted)
    expect(button(t('edit'), hosted).disabled).toBe(false)
    await act(async () => finish({ model: 'late', elapsedMs: 1 }))
    expect(container.textContent).not.toContain('late')
  })
  it('cancels tests and ignores late results after cancellation and disposal', async () => {
    const api = apiFixture(saved)
    let finish!: (value: unknown) => void
    api.test.mockImplementation(() => new Promise(resolve => { finish = resolve }))
    await render(<ProvidersSection api={api} t={t} />)
    await click(t('modelsAndTest', { count: 2 }), card('TypeSafe'))
    await click(t('test'), card('TypeSafe')); await click(t('cancel'), card('TypeSafe'))
    expect(api.test.mock.calls[0][2].aborted).toBe(true)
    await act(async () => finish({ model: 'late', elapsedMs: 1 }))
    expect(container.textContent).not.toContain('late')
    await click(t('test'), card('TypeSafe'))
    await render(null)
    expect(api.test.mock.calls[1][2].aborted).toBe(true)
    await act(async () => finish({ model: 'late', elapsedMs: 1 }))
  })
  it('shows a retryable load error and read-only configuration while allowing details', async () => {
    const api = apiFixture({ ...saved, writable: false })
    api.state.mockRejectedValueOnce(new Error('secret-error'))
    await render(<ProvidersSection api={api} t={t} />)
    expect(container.textContent).toContain(t('error.failed'))
    expect(container.textContent).not.toContain('secret-error')
    await click(t('refresh'))
    expect(container.textContent).toContain(t('readOnly'))
    expect(button(t('add')).disabled).toBe(true)
    expect(button(t('edit'), card('TypeSafe')).disabled).toBe(true)
    expect(button(t('remove'), card('TypeSafe')).disabled).toBe(true)
    await click(t('modelsAndTest', { count: 2 }), card('TypeSafe'))
    expect(card('TypeSafe').textContent).toContain('jev-preview')
    expect(button(t('test'), card('TypeSafe')).disabled).toBe(false)
  })
  it('locks add modes, fields, save and cancellation while saving, then shows the persisted compact row', async () => {
    const api = apiFixture()
    let finish!: (state: ProvidersState) => void
    api.save.mockImplementationOnce(() => new Promise(resolve => { finish = resolve }))
    await render(<ProvidersSection api={api} t={t} />)
    await click(t('add')); await modelInput(1, 'jev-preview'); await input(t('apiKey'), 'offline-test-key'); await submit()
    expect(tab(t('knownMode')).disabled).toBe(true)
    expect(tab(t('customMode')).disabled).toBe(true)
    expect(activeEditor().querySelector('fieldset')?.disabled).toBe(true)
    expect(button(t('cancel'), activeEditor()).disabled).toBe(true)
    expect(button(t('saving'), activeEditor()).disabled).toBe(true)
    await submit()
    expect(api.save).toHaveBeenCalledTimes(1)
    await act(async () => finish(saved))
    expect(container.querySelector('form')).toBeNull()
    expect(card('TypeSafe').textContent).toContain(t('modelsAndTest', { count: 2 }))
  })
})

describe('editor and locale lifecycle', () => {
  it('explicitly clears a saved key, omits secret values, and preserves exact explicit IDs', async () => {
    const save = vi.fn()
    await render(<ProviderEditor provider={provider} revision="r2" busy={false} t={t} onSave={save} onCancel={vi.fn()} />)
    await input(t('apiKey'), 'new-key')
    await act(async () => (container.querySelector('input[type="checkbox"]') as HTMLInputElement).click())
    expect((container.querySelector('input[type="password"]') as HTMLInputElement).value).toBe('')
    await submit()
    const change = save.mock.calls[0][0] as ProviderChange
    expect(change.clearKey).toBe(true); expect(change.apiKey).toBeUndefined()
    expect(change.provider.models).toEqual(provider.models)
    expect(change.provider).not.toHaveProperty('modelIds')
  })
  it('confirms discarding edits and warns on unload', async () => {
    const cancel = vi.fn()
    const confirm = vi.spyOn(window, 'confirm').mockReturnValue(false)
    await render(<ProviderEditor revision="r1" busy={false} t={t} onSave={vi.fn()} onCancel={cancel} />)
    await input(t('name'), 'Draft')
    const event = new Event('beforeunload', { cancelable: true }); window.dispatchEvent(event)
    expect(event.defaultPrevented).toBe(true)
    await click(t('cancel')); expect(cancel).not.toHaveBeenCalled()
    confirm.mockReturnValue(true); await click(t('cancel')); expect(cancel).toHaveBeenCalledOnce()
  })
  it('leaves pristine drafts without prompting and disables submission while busy', async () => {
    const cancel = vi.fn(); const confirm = vi.spyOn(window, 'confirm'); const save = vi.fn()
    await render(<ProviderEditor revision="r1" busy={false} t={t} onSave={save} onCancel={cancel} />)
    await click(t('cancel')); expect(confirm).not.toHaveBeenCalled(); expect(cancel).toHaveBeenCalledOnce()
    await render(<ProviderEditor revision="r1" busy={true} t={t} onSave={save} onCancel={cancel} />)
    await submit(); expect(save).not.toHaveBeenCalled()
  })
  it('keeps dictionary parity and interpolation semantics', () => {
    expect(Object.keys(en).sort()).toEqual(Object.keys(zh).sort())
    expect(interpolate('Hi {name}; {unknown}', { name: 'A' })).toBe('Hi A; {unknown}')
    expect(interpolate('plain')).toBe('plain')
    expect(t('saved')).toBe(en.saved)
    expect(t('modelsAndTest', { count: 2 })).toBe('Models and test (2)')
  })
  it('registers only the Models footer and disposes dictionaries through effects', () => {
    const cleanup = vi.fn(); const entries: unknown[] = []
    const locale = { register: vi.fn(() => cleanup), bind: vi.fn(() => t) }
    const slots = { inject: vi.fn((_slot, callback) => callback()), register: vi.fn((entry, render) => { entries.push(entry); expect(render().type).toBe(ProvidersSection); return cleanup }) }
    const effects: Array<() => void> = []
    apply({ get: (key: string) => ({ locale, slots })[key as 'locale' | 'slots'], effect: (factory: () => () => void) => effects.push(factory()) } as unknown as Context)
    expect(inject).toEqual(['slots', 'locale'])
    expect(entries).toEqual([{ name: 'settings.models.footer', id: 'dsh-next-decisions', order: 20 }])
    expect(locale.register).toHaveBeenCalledTimes(2)
    effects.forEach(off => off()); expect(cleanup).toHaveBeenCalledTimes(2)
    expect(() => apply({ get: () => undefined } as unknown as Context)).not.toThrow()
  })
})
